### PR TITLE
Create demo with minimal feature set

### LINKED ISSUE #12: Reduce demo to minimal features
We should reduce the demo (or produce another version, titled `minimum.js`), to have a reduced UI.

* I think the only options needed are the shown in the screenshot below
* we don't need the editable meta-schema - we'll hard-code use of this one
* show the preview mode beneath the current editor, rather than to the left
* 

image

### PR DESCRIPTION
**Pull request by Franciman**
Fixes #12

### CODE REVIEW

**Comment by Franciman** [comment]
The JSON Editor has the required options set.
I also removed the meta schema editor.
One question, though: Which layout do we need to use for objects in the *Schema* editor? Normal or grid? I think normal makes more sense in the *Schema* editor, because using grid becomes a bit messy.

**Comment by IanMayo** [comment]
I was playing with the minimal layout earlier.  Yes, it make sense to stick to `normal`, and then remove the `layout` drop-down.

**Comment by IanMayo** [comment]
You should also modify the front page readme to include both links

**Comment by IanMayo** [comment]
Aah, we can actually link to working versions, just use this prefix:
https://deepbluecltd.github.io/json-schema-editor/

**Pull request merged**
