### PR TITLE
Reduce the available top level schemas to just Object

### LINKED ISSUE #4: Restrict top level types
To make this schema editor as efficient as possible, I propose we reduce the choices when possible.

Currently the list of top-level object types is quite large:
image

I propose we trim it to `object` and `array`.  (I'm almost tempted to drop the `array` type, since the object we're creating will still be some logical collection of items.  But, let's defer that).

Even if the user wants to just capture the name of a person (as a String) it would still be "good practice" to include that in a recognisable object:

````
{
  "type": "object",
  "title": "Person",
  "description":"Definition of a person",
  "properties": {
    "Name": {
      "title": "Name",
      "type": "string",
      "description": "Name of this person"
    }
  },
  "required":["Name"]
}
````
rather than:
````
{
  "title": "Name",
  "type": "string",
  "description": "Name of this person"
}
````

### PR DESCRIPTION
**Pull request by Franciman**
Fixes #4

### CODE REVIEW

**Comment by IanMayo** [comment]
@Franciman - note what I put into the first comment.  That "trick" means GitHub will close the issue when this PR gets merged.

**Comment by IanMayo** [comment]
In the issue (#4) we've agreed to limit the top level element type to `object`.  I'll merge this once @Franciman has updated the schema.

**Comment by Franciman** [comment]
I couldn't avoid the drop down menu at the top, for now, since if I don't specify the `oneOf` keyword, `additionalProperties: false` doesn't work as we want, but enforces that only the properties specified in "object" be available, while properties specified in "schemaBase" can't be used.
Instead wrapping `oneOf` around the `"$ref":"#/definitions/object"` works as intended.

@pmk65 any idea why this happens?

**Comment by pmk65** [comment]
@Franciman There's currently a lot of open issues on [JSON-Editor](https://github.com/json-editor/json-editor/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+oneof) regarding oneOf/anyOf, so there's a chance you ran into one of those. (I haven't used oneOf/anyOf myself, so I haven't tried fixing any of those.)

**Comment by Franciman** [comment]
Oh, so all this schema may be working by chance... I'm gonna skim through them, thanks.
The use case we need is:
I have 3 different types of objects, but they share a common set of properties, so I use $ref to validate the common part, and then for each object I also add the specific properties for that type of object.
Now I want to enforce that only these two categories of properties be available.

**Comment by IanMayo** [comment]
@Franciman - when I add my first property ('name') to the schema I get an error.  I can only remove the error by removing the property:

image

**Pull request closed without merging**
